SEMANA10/dia3/ecommerce-aws/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('web.urls')),
    path('admin/', admin.site.urls),
    path('paypal/', include("paypal.standard.ipn.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

SEMANA10/dia3/ecommerce-aws/web/urls.py
from django.urls import path

from . import views

app_name='web'

urlpatterns = [
    path('', views.index,name='index'),
    path('producto/<int:producto_id>',views.producto,name='producto'),
    path('carrito',views.carrito,name='carrito'),
    path('agregarCarrito/<int:producto_id>',views.agregarCarrito,name='agregarCarrito'),
    path('eliminarCarrito/<int:producto_id>',views.eliminarProductoCarrito,name='eliminarCarrito'),
    path('limpiarCarrito',views.limpiarCarrito,name='limpiarCarrito'),
    path('crearUsuario',views.crearUsuario,name='crearUsuario'),
    path('cuenta',views.cuentaUsuario,name='cuentaUsuario'),
    path('login',views.loginUsuario,name='loginUsuario'),
    path('actualizarCliente',views.actualizarCliente,name='actualizarCliente'),
    path('registrarPedido',views.registrarPedido,name='registrarPedido'),
    path('confirmarPedido',views.confirmarPedido,name='confirmarPedido'),
    path('gracias',views.gracias,name='gracias')
]

SEMANA10/dia3/ecommerce-aws/web/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'tbl_categoria'
        
    def __str__(self):
        return self.nombre
    
class Marca(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'tbl_marca'
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.RESTRICT)
    marca= models.ForeignKey(Marca,on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=254)
    descripcion = models.TextField(null=True)
    detalle = models.TextField(null=True)
    caracteristicas = models.TextField(null=True)
    precio = models.DecimalField(max_digits=10,decimal_places=2)
    imagen = models.ImageField(upload_to='productos',blank=True)
    
    class Meta:
        db_table = 'tbl_producto'
    
    def __str__(self):
        return self.nombre
    
class ProductoImagen(models.Model):
    producto = models.ForeignKey(Producto,on_delete=models.RESTRICT)
    imagen = models.ImageField(upload_to='galeria',blank=True)
    
    class Meta:
        db_table = 'tbl_producto_imagen'
        
    def __str__(self):
        return self.producto.nombre
    
class ProductoRelacionado(models.Model):
    producto = models.ForeignKey(Producto,related_name='Principal',on_delete=models.RESTRICT)
    relacionado = models.ForeignKey(Producto,related_name='Relacionado',on_delete=models.RESTRICT)
    
    class Meta:
        db_table = 'tbl_producto_relacionado'
        
    def __str__(self):
        return self.relacionado.nombre
    
from django.contrib.auth.models import User
    
class Cliente(models.Model):
    usuario = models.OneToOneField(User,on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=254)
    dni = models.CharField(max_length=8)
    sexo = models.CharField(max_length=1)
    telefono = models.CharField(max_length=20)
    fecha_nacimiento = models.DateField(null=True)
    direccion = models.TextField()
    
    class Meta:
        db_table = 'tbl_cliente'
    
    def __str__(self):
        return self.nombre
    
class Pedido(models.Model):
    ESTADO_CHOICES = (
        ('0','Solicitado'),
        ('1','Pagado')
    )
    
    cliente = models.ForeignKey(Cliente,on_delete=models.RESTRICT)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    nro_pedido = models.CharField(max_length=20,null=True)
    monto_total = models.DecimalField(max_digits=10,decimal_places=2)
    estado = models.CharField(max_length=1,default='0',choices=ESTADO_CHOICES)
    forma_pago = models.CharField(max_length=20,null=True)
    codigo_pago = models.CharField(max_length=20,null=True)
    
    class Meta:
        db_table = 'tbl_pedido'
        
    def __str__(self):
        return self.nro_pedido
    
class PedidoDetalle(models.Model):
    pedido = models.ForeignKey(Pedido,on_delete=models.RESTRICT)
    producto = models.ForeignKey(Producto,on_delete=models.RESTRICT)
    cantidad = models.IntegerField(default=1)
    subtotal = models.DecimalField(max_digits=10,decimal_places=2)
    
    class Meta:
        db_table = 'tbl_pedido_detalle'
        
    def __str__(self):
        return self.producto.nombre
    
    

SEMANA10/dia3/ecommerce-aws/web/templates/includes/catalog/breadcrumb.html
<ul class="b-crumbs">
    <li><a href="index.html">Home</a></li>
    <li><a href="catalog-gallery.html">Catalog</a></li>
    <li>Product</li>
</ul>

SEMANA10/dia3/ecommerce-aws/web/templates/includes/catalog/producto_galeria.html
<div class="prod-slider-wrap prod-slider-shown">
    <div class="flexslider prod-slider" id="prod-slider">
        <ul class="slides">
            {% for prodimg in producto.productoimagen_set.all %}
                <li>
                    <a data-fancybox-group="prod" class="fancy-img" href="{{prodimg.imagen.url}}">
                        <img src="{{prodimg.imagen.url}}" alt="">
                    </a>
                </li>
            {% endfor %}
        </ul>
        <div class="prod-slider-count"><p><span class="count-cur">1</span> / <span class="count-all">2</span></p><p class="hover-label prod-slider-zoom"><i class="icon ion-search"></i><span>Zoom In</span></p></div>
    </div>
    <div class="flexslider prod-thumbs" id="prod-thumbs">
        <ul class="slides">
            {% for prodimg in producto.productoimagen_set.all %}
                <li>
                    <img src="{{prodimg.imagen.url}}" alt="">
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

SEMANA10/dia3/ecommerce-aws/web/templates/includes/catalog/producto_info.html
<div class="prod-tabs-wrap">
    <ul class="prod-tabs">
        <li id="prod-desc" class="active" data-prodtab-num="1">
            <a data-prodtab="#prod-tab-1" href="#">Description</a>
        </li>
        <li data-prodtab-num="2" id="prod-props">
            <a data-prodtab="#prod-tab-2" href="#">Additional information</a>
        </li>
        <li data-prodtab-num="3" id="prod-reviews">
            <a data-prodtab="#prod-tab-3" href="#">Reviews (7)</a>
        </li>
        <li class="prod-tabs-addreview">Add a review</li>	</ul>
    <div class="prod-tab-cont">
        <p data-prodtab-num="1" class="prod-tab-mob active" data-prodtab="#prod-tab-1">Description</p>
        <div class="prod-tab page-styling prod-tab-desc" id="prod-tab-1">
            <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
        </div>
        <p data-prodtab-num="2" class="prod-tab-mob" data-prodtab="#prod-tab-2">Additional information</p>
        <div class="prod-tab" id="prod-tab-2">
            <dl class="prod-tab-props">
                <dt>Weight</dt>
                <dd>1 kg</dd>
                <dt>Dimensions</dt>
                <dd>4 x 50 cm</dd>
                <dt>Сolor</dt>
                <dd><p><a href="#">Blue</a>, <a href="#">Green</a></p></dd>
                <dt>Manufacturer</dt>
                <dd><p><a href="#">Germany</a></p></dd>
                <dt>Material</dt>
                <dd><p><a href="#">Metall</a>, <a href="#">Plastic</a></p></dd>
            </dl>
        </div>
        <p data-prodtab-num="3" class="prod-tab-mob" data-prodtab="#prod-tab-3">Reviews (7)</p>
        <div class="prod-tab prod-reviews" id="prod-tab-3">
            <div id="reviews">
                <div id="review_form_wrapper" class="prod-addreview-form">
                    <div id="review_form">
                        <div id="respond" class="comment-respond">
                            <p class="prod-tab-addreview" id="reply-title">Add a Review</p>
                            <form action="#" method="post" id="commentform" class="comment-form">
                                <div class="comment-form-rating">
                                    <p class="stars"><span><a class="star-1" href="#">1</a><a class="star-2" href="#">2</a><a class="star-3" href="#">3</a><a class="star-4" href="#">4</a><a class="star-5" href="#">5</a></span></p>
                                    <select>
                                        <option value="">Rate…</option>
                                        <option value="5">Perfect</option>
                                        <option value="4">Good</option>
                                        <option value="3">Average</option>
                                        <option value="2">Not that bad</option>
                                        <option value="1">Very Poor</option>
                                    </select>
                                </div>
                                <textarea placeholder="Review"></textarea>
                                <input type="submit" class="submit" value="Add a Review">
                            </form>
                        </div>
                    </div>
                </div>
                <ul id="comments">
                    <li class="prod-review">
                        <div>
                            <h3>admin</h3>
                            <p class="prod-review-rating" title="Rated 5 out of 5">
                                <i class="rating-ico"></i>
                                <i class="rating-ico"></i>
                                <i class="rating-ico"></i>
                                <i class="rating-ico"></i>
                                <i class="rating-ico"></i>
                                <time datetime="2017-05-09T14:16:55+00:00">May 9, 2017</time>
                            </p>
                            <p>Aliquam ligula quam, vehicula non porta at, venenatis ac purus. Pellentesque pharetra, turpis sit amet elementum faucibus, tellus nisi condimentum metus, nec scelerisque tortor velit ac purus. Aenean interdum velit quis nisi rhoncus ullamcorper. Cras lorem metus, imperdiet vel tortor vitae, malesuada pellentesque felis. Nulla varius mi a varius semper. Sed tristique ligula tincidunt pellentesque rhoncus. Praesent purus urna, imperdiet in pellentesque sed, hendrerit quis mauris. Maecenas consequat ultrices augue ac tempor. Etiam semper eu ligula id iaculis. Morbi scelerisque neque at velit porta, et fringilla nisl pulvinar. Duis at rhoncus est, nec cursus orci. Nunc malesuada tellus magna, in feugiat mauris placerat eu. Nullam elementum est id aliquam imperdiet.</p>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

SEMANA10/dia3/ecommerce-aws/web/templates/includes/catalog/productos.html
<div class="row prod-items prod-items-2">
    {% for producto in productos %}
    <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
        <div class="sectgl prod-i">
            <div class="prod-i-top">
                <a class="prod-i-img" href="#">
                    <img src="{{producto.imagen.url}}" alt="">
                </a>
                <div class="prod-i-actions">
                    <div class="prod-i-actions-in">
                        <div class="prod-li-favorites">
                            <a href="wishlist.html" class="hover-label add_to_wishlist"><i class="icon ion-heart"></i><span>Add to Wishlist</span></a>
                        </div>
                        <p class="prod-quickview">
                            <a href="#" class="hover-label quick-view"><i class="icon ion-plus"></i><span>Quick View</span></a>
                        </p>
                        <p class="prod-i-cart">
                            <a href="{% url 'web:agregarCarrito' producto.id %}" class="hover-label prod-addbtn"><i class="icon ion-android-cart"></i><span>Add to Cart</span></a>
                        </p>
                        <p class="prod-li-compare">
                            <a href="compare.html" class="hover-label prod-li-compare-btn"><span>Compare</span><i class="icon ion-arrow-swap"></i></a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="prod-i-bot">
                <div class="prod-i-info">
                    <p class="prod-i-price">${{producto.precio}}</p>
                    <p class="prod-i-categ"><a href="catalog-gallery.html">{{producto.marca}}</a></p>
                </div>
                <h3 class="prod-i-ttl"><a href="{% url 'web:producto' producto.id %}">{{producto.nombre}}</a></h3>
            </div>
        </div>
    </article>
    {% endfor %}
</div>
<ul class="page-numbers">
    <li><span class="page-numbers current">1</span></li>
    <li><a class="page-numbers" href="#">2</a></li>
    <li><a class="page-numbers" href="#">3</a></li>
    <li><a class="page-numbers" href="#">4</a></li>
    <li><a class="next page-numbers" href="#"><i class="fa fa-angle-right"></i></a></li>
</ul>

SEMANA10/dia3/ecommerce-aws/web/templates/includes/catalog/relacionados.html
<h2 class="prod-related-ttl">Productos Relacionados</h2>
    <div class="row prod-items prod-items-4">
        {% for relacionado in producto.productorelacionado_set.all %}
        <article class="cf-sm-6 cf-md-6 cf-lg-3 col-xs-6 col-sm-6 col-md-6 col-lg-3 sectgl-item sectgl-item">
            <div class="sectgl prod-i">
                <div class="prod-i-top">
                    <a class="prod-i-img" href="product.html">
                        <img src="{{relacionado.imagen.url}}" alt="">
                    </a>
                    <div class="prod-i-actions">
                        <div class="prod-i-actions-in">
                            <div class="prod-li-favorites">
                                <a href="wishlist.html" class="hover-label add_to_wishlist"><i class="icon ion-heart"></i><span>Add to Wishlist</span></a>
                            </div>
                            <p class="prod-quickview">
                                <a href="#" class="hover-label quick-view"><i class="icon ion-plus"></i><span>Quick View</span></a>
                            </p>
                            <p class="prod-i-cart">
                                <a href="#" class="hover-label prod-addbtn"><i class="icon ion-android-cart"></i><span>Add to Cart</span></a>
                            </p>
                            <p class="prod-li-compare">
                                <a href="compare.html" class="hover-label prod-li-compare-btn"><span>Compare</span><i class="icon ion-arrow-swap"></i></a>
                            </p>
                        </div>
                    </div>
                    <p class="prod-i-badge"><span>Sale</span></p>
                </div>
                <div class="prod-i-bot">
                    <div class="prod-i-info">
                        <p class="prod-i-price">${{relacionado.precio}}</p>
                        <p class="prod-i-categ"><a href="catalog-gallery.html">{{relacionado.categoria}}</a></p>
                    </div>
                    <h3 class="prod-i-ttl"><a href="product.html">{{relacionado.nombre}}</a></h3>
                </div>
            </div>
        </article>
        {% endfor %}                                                                             
    </div>

SEMANA10/dia3/ecommerce-aws/web/templates/includes/catalog/sidebar.html
<aside class="blog-sb-widgets section-sb" id="section-sb">
    <div class="theiaStickySidebar">
        <p class="section-filter-toggle filter_hidden">
            <a href="#" id="section-filter-toggle-btn">Show Filter</a>
        </p>
        <div class="section-filter">
            <div class="section-filter">
                <div class="blog-sb-widget multishopcategories_widget">
                    <h3 class="widgettitle">Categorias</h3>
                    <div class="section-sb-current">
                        <ul class="section-sb-list">
                            {% for categoria in categorias %}
                            <li>
                                <a href="#"><span class="section-sb-label">{{categoria.nombre}} <span class="count">{{categoria.producto_set.all.count}}</span></span></a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="blog-sb-widget multishopbrands_widget">
                    <h3 class="widgettitle">Marcas</h3>
                    <ul class="brands-list-sb">
                        {% for marca in marcas %}
                        <li>
                            <a href="#">{{marca.nombre}} <span class="count">{{marca.producto_set.all.count}}</span></a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</aside>