SEMANA10/dia3/ecommerce-aws/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('web.urls')),
    path('admin/', admin.site.urls),
    path('paypal/', include("paypal.standard.ipn.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

SEMANA10/dia3/ecommerce-aws/web/urls.py
from django.urls import path

from . import views

app_name='web'

urlpatterns = [
    path('', views.index,name='index'),
    path('producto/<int:producto_id>',views.producto,name='producto'),
    path('carrito',views.carrito,name='carrito'),
    path('agregarCarrito/<int:producto_id>',views.agregarCarrito,name='agregarCarrito'),
    path('eliminarCarrito/<int:producto_id>',views.eliminarProductoCarrito,name='eliminarCarrito'),
    path('limpiarCarrito',views.limpiarCarrito,name='limpiarCarrito'),
    path('crearUsuario',views.crearUsuario,name='crearUsuario'),
    path('cuenta',views.cuentaUsuario,name='cuentaUsuario'),
    path('login',views.loginUsuario,name='loginUsuario'),
    path('actualizarCliente',views.actualizarCliente,name='actualizarCliente'),
    path('registrarPedido',views.registrarPedido,name='registrarPedido'),
    path('confirmarPedido',views.confirmarPedido,name='confirmarPedido'),
    path('gracias',views.gracias,name='gracias')
]

SEMANA10/dia3/ecommerce-aws/web/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'tbl_categoria'
        
    def __str__(self):
        return self.nombre
    
class Marca(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'tbl_marca'
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.RESTRICT)
    marca= models.ForeignKey(Marca,on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=254)
    descripcion = models.TextField(null=True)
    detalle = models.TextField(null=True)
    caracteristicas = models.TextField(null=True)
    precio = models.DecimalField(max_digits=10,decimal_places=2)
    imagen = models.ImageField(upload_to='productos',blank=True)
    
    class Meta:
        db_table = 'tbl_producto'
    
    def __str__(self):
        return self.nombre
    
class ProductoImagen(models.Model):
    producto = models.ForeignKey(Producto,on_delete=models.RESTRICT)
    imagen = models.ImageField(upload_to='galeria',blank=True)
    
    class Meta:
        db_table = 'tbl_producto_imagen'
        
    def __str__(self):
        return self.producto.nombre
    
class ProductoRelacionado(models.Model):
    producto = models.ForeignKey(Producto,related_name='Principal',on_delete=models.RESTRICT)
    relacionado = models.ForeignKey(Producto,related_name='Relacionado',on_delete=models.RESTRICT)
    
    class Meta:
        db_table = 'tbl_producto_relacionado'
        
    def __str__(self):
        return self.relacionado.nombre
    
from django.contrib.auth.models import User
    
class Cliente(models.Model):
    usuario = models.OneToOneField(User,on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=254)
    dni = models.CharField(max_length=8)
    sexo = models.CharField(max_length=1)
    telefono = models.CharField(max_length=20)
    fecha_nacimiento = models.DateField(null=True)
    direccion = models.TextField()
    
    class Meta:
        db_table = 'tbl_cliente'
    
    def __str__(self):
        return self.nombre
    
class Pedido(models.Model):
    ESTADO_CHOICES = (
        ('0','Solicitado'),
        ('1','Pagado')
    )
    
    cliente = models.ForeignKey(Cliente,on_delete=models.RESTRICT)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    nro_pedido = models.CharField(max_length=20,null=True)
    monto_total = models.DecimalField(max_digits=10,decimal_places=2)
    estado = models.CharField(max_length=1,default='0',choices=ESTADO_CHOICES)
    forma_pago = models.CharField(max_length=20,null=True)
    codigo_pago = models.CharField(max_length=20,null=True)
    
    class Meta:
        db_table = 'tbl_pedido'
        
    def __str__(self):
        return self.nro_pedido
    
class PedidoDetalle(models.Model):
    pedido = models.ForeignKey(Pedido,on_delete=models.RESTRICT)
    producto = models.ForeignKey(Producto,on_delete=models.RESTRICT)
    cantidad = models.IntegerField(default=1)
    subtotal = models.DecimalField(max_digits=10,decimal_places=2)
    
    class Meta:
        db_table = 'tbl_pedido_detalle'
        
    def __str__(self):
        return self.producto.nombre
    
    

SEMANA10/dia3/ecommerce-aws/web/templates/carrito.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class="maincont-ttl">Cart</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>Cart</li>
    </ul>
    <div class="page-styling">
    <div class="woocommerce prod-litems section-list">
        {% for key,value in request.session.cart.items %}
            <article class="prod-li sectls">
                <div class="prod-li-inner">
                    <a href="#" class="prod-li-img">
                        <img src="{{value.imagen}}" alt="">
                    </a>
                    <div class="prod-li-cont">
                        <div class="prod-li-ttl-wrap">
                            <p>
                                <a href="#">{{value.categoria}}</a>
                            </p>
                            <h3><a href="#">{{value.nombre}}</a></h3>
                        </div><!--
        No Space
        --><div class="prod-li-prices">
                        <div class="prod-li-price-wrap">
                            <p>Precio</p>
                            <p class="prod-li-price">${{value.precio}}</p>
                        </div>
                        <div class="prod-li-qnt-wrap">
                            <p class="qnt-wrap prod-li-qnt">
                                <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                <input type="text" value="{{value.cantidad}}">
                                <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                            </p>
                        </div>
                        <div class="prod-li-total-wrap">
                            <p>Total</p>
                            <p class="prod-li-total">${{value.subtotal}}</p>
                        </div>
                    </div><!--
    No Space
    --></div>
                    <div class="prod-li-info">
                        <div class="prod-li-rating-wrap">
                            <p data-rating="5" class="prod-li-rating">
                                <i class="rating-ico" title="1"></i><i class="rating-ico" title="2"></i><i class="rating-ico" title="3"></i><i class="rating-ico" title="4"></i><i class="rating-ico" title="5"></i>
                            </p>
                            <p class="prod-li-rating-count">12</p>
                        </div>
                        <p class="prod-li-add">
                            <a href="{% url 'web:eliminarCarrito' value.producto_id %}" class="button hover-label prod-addbtn"><i class="icon ion-close-round"></i><span>Eliminar</span></a>
                        </p>
                        <p class="prod-li-compare">
                            <a href="compare.html" class="hover-label prod-li-compare-btn"><span>Compare</span><i class="icon ion-arrow-swap"></i></a>
                        </p>
                        <p class="prod-quickview">
                            <a href="#" class="hover-label quick-view"><i class="icon ion-plus"></i><span>Quick View</span></a>
                        </p>
                        <div class="prod-li-favorites">
                            <a href="wishlist.html" class="hover-label add_to_wishlist"><i class="icon ion-heart"></i><span>Add to Wishlist</span></a>
                        </div>
                        <p class="prod-li-information">
                            <a href="#" class="hover-label"><i class="icon ion-more"></i><span>Show Information</span></a>
                        </p>
                    </div>
                </div>
                <div class="page-styling prod-li-informations">

                    <dl class="prod-li-props">
                        <dt>Brand:</dt>
                        <dd><a href="#">AIR</a></dd>
                        <dt>Weight:</dt>
                        <dd>1 kg</dd>
                        <dt>Dimensions:</dt>
                        <dd>4 x 50 cm</dd>
                        <dt>Сolor:</dt>
                        <dd><a href="#" rel="tag">Black</a>, <a href="#" rel="tag">Green</a></dd>
                        <dt>Manufacturer:</dt>
                        <dd><a href="#">France</a></dd>
                        <dt>Material:</dt>
                        <dd><a href="#" rel="tag">Metall</a>, <a href="#" rel="tag">Plastic</a>, <a href="#" rel="tag">Rubber</a></dd>
                    </dl>
                </div>
            </article>
        {% endfor %}
    </div>


    <div class="cart-actions">
        <div class="coupon">
            <input type="text" placeholder="Coupon code">
            <input type="submit" class="button" value="Apply">
        </div>
        <div class="cart-collaterals">
            <a href="{% url 'web:limpiarCarrito' %}" class="checkout-button button">Limpiar Carrito</a>
            <a href="{% url 'web:registrarPedido' %}" class="checkout-button button">Registrar Pedido</a>
            <div class="order-total">
                <p class="cart-totals-ttl">Total</p>
                <p class="cart-totals-val">${{request.session.total}}</p>
            </div>
        </div>
    </div>


</div>
{% endblock %}

SEMANA10/dia3/ecommerce-aws/web/templates/compra.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">Nro Pedido : {{pedido.nro_pedido}}</h1>
<h1 class="maincont-ttl">Fecha : {{pedido.fecha_registro}}</h1>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos del Cliente</h2>
                    <p>
                        <label for="nombre">DNI : {{pedido.cliente.dni}}</label>
                    </p>
                    <p>
                        <label for="nombre">Nombres : {{user.first_name}}</label>
                    </p>
                    <p>
                        <label for="nombre">Apellidos : {{user.last_name}}</label>
                    </p>
                    
                </div>
                <div class="auth-col">
                    <h2>Datos de Envio</h2>
                    <p>
                        <label for="nombre">Dirección : {{pedido.cliente.direccion}}</label>
                        
                    </p>
                    <p>
                        <label for="nombre">Telefono : {{pedido.cliente.telefono}}</label>
                        
                    </p>
                    <p>
                        <label for="nombre">Email : {{user.email}}</label>
                        
                    </p>
                </div>
            </div>
        </div>
    </article>
    <article class="page-cont">
        <h2>Productos a Comprar</h2>
        <div class="page-styling">
            <div class="woocommerce prod-litems section-list">
                {% for detalle in pedido.pedidodetalle_set.all %}
                    <article class="prod-li sectls">
                        <div class="prod-li-inner">
                            <a href="#" class="prod-li-img">
                                <img src="{{detalle.producto.imagen.url}}" alt="">
                            </a>
                            <div class="prod-li-cont">
                                <div class="prod-li-ttl-wrap">
                                    <p>
                                        <a href="#">{{detalle.producto.categoria}}</a>
                                    </p>
                                    <h3><a href="#">{{detalle.producto.nombre}}</a></h3>
                                </div><!--
                No Space
                --><div class="prod-li-prices">
                                <div class="prod-li-price-wrap">
                                    <p>Precio</p>
                                    <p class="prod-li-price">${{detalle.producto.precio}}</p>
                                </div>
                                <div class="prod-li-qnt-wrap">
                                    <p class="qnt-wrap prod-li-qnt">
                                        <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                        <input type="text" value="{{detalle.cantidad}}">
                                        <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                                    </p>
                                </div>
                                <div class="prod-li-total-wrap">
                                    <p>Total</p>
                                    <p class="prod-li-total">${{detalle.subtotal}}</p>
                                </div>
                            </div><!--
            No Space
            -->     </div>
                        </div>
                    </article>
                {% endfor %}
            </div>
        
            <div class="cart-actions">
                <div class="coupon">
                    {{formPaypal}}
                </div>
                <div class="cart-collaterals">
                    <div class="order-total">
                        <p class="cart-totals-ttl">Total</p>
                        <p class="cart-totals-val">${{pedido.monto_total}}</p>
                    </div>
                </div>
            </div>        
    </article>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <p class="auth-submit">
                        {{formPaypal.render}}
                    </p>
                </div>
            </div>
        </div>
    </article>
{% endblock %}

SEMANA10/dia3/ecommerce-aws/web/templates/cuenta.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class="maincont-ttl">Bienvenido {{user.username}}</h1>
    <h2>{{mensaje}}</h2>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Login</h2>
                    <form method="post" class="login" action="{% url 'web:actualizarCliente' %}">
                        {% csrf_token %}
                        {{frmCliente.as_p}}
                        <p class="auth-submit">
                            <input type="submit" value="Actualizar Datos">
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </article>
{% endblock %}

SEMANA10/dia3/ecommerce-aws/web/templates/gracias.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">GRACIAS POR TU COMPRA</h1>
<h1 class="maincont-ttl">Nro Pedido : {{pedido.nro_pedido}}</h1>
<h1 class="maincont-ttl">Forma de Pago : {{pedido.forma_pago}}</h1>
<h1 class="maincont-ttl">Codigo de Pago : {{pedido.codigo_pago}}</h1>
<h1 class="maincont-ttl">Fecha : {{pedido.fecha_registro}}</h1>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos del Cliente</h2>
                    <p>
                        <label for="nombre">DNI : {{pedido.cliente.dni}}</label>
                    </p>
                    <p>
                        <label for="nombre">Nombres : {{user.first_name}}</label>
                    </p>
                    <p>
                        <label for="nombre">Apellidos : {{user.last_name}}</label>
                    </p>
                    
                </div>
                <div class="auth-col">
                    <h2>Datos de Envio</h2>
                    <p>
                        <label for="nombre">Dirección : {{pedido.cliente.direccion}}</label>
                        
                    </p>
                    <p>
                        <label for="nombre">Telefono : {{pedido.cliente.telefono}}</label>
                        
                    </p>
                    <p>
                        <label for="nombre">Email : {{user.email}}</label>
                        
                    </p>
                </div>
            </div>
        </div>
    </article>
    <article class="page-cont">
        <h2>Productos comprados</h2>
        <div class="page-styling">
            <div class="woocommerce prod-litems section-list">
                {% for detalle in pedido.pedidodetalle_set.all %}
                    <article class="prod-li sectls">
                        <div class="prod-li-inner">
                            <a href="#" class="prod-li-img">
                                <img src="{{detalle.producto.imagen.url}}" alt="">
                            </a>
                            <div class="prod-li-cont">
                                <div class="prod-li-ttl-wrap">
                                    <p>
                                        <a href="#">{{detalle.producto.categoria}}</a>
                                    </p>
                                    <h3><a href="#">{{detalle.producto.nombre}}</a></h3>
                                </div><!--
                No Space
                --><div class="prod-li-prices">
                                <div class="prod-li-price-wrap">
                                    <p>Precio</p>
                                    <p class="prod-li-price">${{detalle.producto.precio}}</p>
                                </div>
                                <div class="prod-li-qnt-wrap">
                                    <p class="qnt-wrap prod-li-qnt">
                                        <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                        <input type="text" value="{{detalle.cantidad}}">
                                        <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                                    </p>
                                </div>
                                <div class="prod-li-total-wrap">
                                    <p>Total</p>
                                    <p class="prod-li-total">${{detalle.subtotal}}</p>
                                </div>
                            </div><!--
            No Space
            -->     </div>
                        </div>
                    </article>
                {% endfor %}
            </div>
        
            <div class="cart-actions">
                <div class="cart-collaterals">
                    <div class="order-total">
                        <p class="cart-totals-ttl">Total</p>
                        <p class="cart-totals-val">${{pedido.monto_total}}</p>
                    </div>
                </div>
            </div>        
    </article>
{% endblock %}

SEMANA10/dia3/ecommerce-aws/web/templates/index.html
{% extends 'layout.html' %}
{% block content %}
<div class="section-top">

    <h1 class="maincont-ttl">Shop</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>Catalog - Gallery</li>
    </ul>
    <div class="section-top-sort">
        <div class="section-view">
            <p>View</p>
            <div class="dropdown-wrap">
                <p class="dropdown-title section-view-ttl">Gallery</p>
                <ul class="dropdown-list">
                    <li>
                        <a href="catalog-list.html">List</a>
                    </li>
                    <li class="active">
                        <a href="catalog-gallery.html">Gallery</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="section-sort">
            <p>Sort</p>
            <div class="dropdown-wrap">
                <p class="dropdown-title section-sort-ttl">Newness</p>
                <ul class="dropdown-list">
                    <li>
                        <a href="#">Popularity</a>
                    </li>
                    <li>
                        <a href="#">Average rating</a>
                    </li>
                    <li class="active">
                        <a href="#">Newness</a>
                    </li>
                    <li>
                        <a href="#">Price: low to high</a>
                    </li>
                    <li>
                        <a href="#">Price: high to low</a>
                    </li>
                </ul>
            </div>
        </div>
        <form method="post" class="products-per-page">
            <p>Per Page</p>
            <select>
                <option value="12" selected="selected">12</option>
                <option value="24">24</option>
                <option value="48">48</option>
                <option value="-1">All</option>
            </select>
        </form>
    </div>
</div>
<!-- To make Sidebar "Not Sticky" just remove  id="section-list-withsb" -->
<div class="section-wrap-withsb">
    {% include 'includes/catalog/sidebar.html' %}
    <div class="section-list-withsb" id="section-list-withsb">
    <div class="theiaStickySidebar">
    {% include 'includes/catalog/productos.html' %}
    </div><!-- .theiaStickySidebar -->
</div><!-- .section-list-withsb -->
</div><!-- .section-wrap-withsb -->
{% endblock %}

SEMANA10/dia3/ecommerce-aws/web/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    {% include 'includes/meta.html' %}
</head>
<body>
<div id="page" class="site">
    {% include 'includes/navBar.html' %}

    {% include 'includes/header.html' %}


    <div id="content" class="site-content">
        <div id="primary" class="content-area">
            <main id="main" class="site-main">
                <div class="cont maincont">

                    {%block content %}
                    {% endblock %}

                </div>
            </main><!-- #main -->
        </div><!-- #primary -->

    </div><!-- #content -->

    {% include 'includes/footer.html' %}

    {% include 'includes/modals.html' %}
</div><!-- #page -->

<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/jquery-plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

SEMANA10/dia3/ecommerce-aws/web/templates/pedido.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">Registro de Compra</h1>
<form method="post" class="login" action="{% url 'web:confirmarPedido' %}">
    {% csrf_token %}
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos del Cliente</h2>
                    <p>
                        <label for="nombre">DNI</label>
                        {{frmCliente.dni}}
                    </p>
                    <p>
                        <label for="nombre">Nombres</label>
                        {{frmCliente.nombre}}
                    </p>
                    <p>
                        <label for="nombre">Apellidos</label>
                        {{frmCliente.apellidos}}
                    </p>
                    
                </div>
                <div class="auth-col">
                    <h2>Datos de Envio</h2>
                    <p>
                        <label for="nombre">Dirección</label>
                        {{frmCliente.direccion}}
                    </p>
                    <p>
                        <label for="nombre">Telefono</label>
                        {{frmCliente.telefono}}
                    </p>
                    <p>
                        <label for="nombre">Email</label>
                        {{frmCliente.email}}
                    </p>
                </div>
            </div>
        </div>
    </article>
    <article class="page-cont">
        <h2>Productos a Comprar</h2>
        <div class="page-styling">
            <div class="woocommerce prod-litems section-list">
                {% for key,value in request.session.cart.items %}
                    <article class="prod-li sectls">
                        <div class="prod-li-inner">
                            <a href="#" class="prod-li-img">
                                <img src="{{value.imagen}}" alt="">
                            </a>
                            <div class="prod-li-cont">
                                <div class="prod-li-ttl-wrap">
                                    <p>
                                        <a href="#">{{value.categoria}}</a>
                                    </p>
                                    <h3><a href="#">{{value.nombre}}</a></h3>
                                </div><!--
                No Space
                --><div class="prod-li-prices">
                                <div class="prod-li-price-wrap">
                                    <p>Precio</p>
                                    <p class="prod-li-price">${{value.precio}}</p>
                                </div>
                                <div class="prod-li-qnt-wrap">
                                    <p class="qnt-wrap prod-li-qnt">
                                        <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                        <input type="text" value="{{value.cantidad}}">
                                        <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                                    </p>
                                </div>
                                <div class="prod-li-total-wrap">
                                    <p>Total</p>
                                    <p class="prod-li-total">${{value.subtotal}}</p>
                                </div>
                            </div><!--
            No Space
            -->     </div>
                        </div>
                    </article>
                {% endfor %}
            </div>
        
            <div class="cart-actions">
                <div class="coupon">
                    <input type="text" placeholder="Coupon code">
                    <input type="submit" class="button" value="Apply">
                </div>
                <div class="cart-collaterals">
                    <div class="order-total">
                        <p class="cart-totals-ttl">Total</p>
                        <p class="cart-totals-val">${{request.session.total}}</p>
                    </div>
                </div>
            </div>        
    </article>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <p class="auth-submit">
                        <input type="submit" value="CONFIRMAR PEDIDO"/>
                    </p>
                </div>
            </div>
        </div>
    </article>
</form>
{% endblock %}

SEMANA10/dia3/ecommerce-aws/web/templates/producto.html
{% extends 'layout.html' %}
{% block content %}
    {% include 'includes/catalog/breadcrumb.html' %}
    <article>
    <div class="prod">
        {% include 'includes/catalog/producto_galeria.html' %}

        <div class="prod-cont">
            <div class="prod-rating-wrap">
                <p data-rating="4" class="prod-rating">
                    <i class="rating-ico" title="1"></i><i class="rating-ico" title="2"></i><i class="rating-ico" title="3"></i><i class="rating-ico" title="4"></i><i class="rating-ico" title="5"></i>
                </p>
                <p class="prod-rating-count">7</p>
            </div>
            <p class="prod-categs"><a href="#">{{producto.categoria}}</a></p>
            <h1>{{producto.nombre}}</h1>
            <div class="variations_form cart">
                <p class="prod-price">${{producto.precio}}</p>
                <p class="prod-excerpt">{{producto.descripcion}}</p>
                <div class="prod-add">
                    <form action="{% url 'web:agregarCarrito' producto.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="button"><i class="icon ion-android-cart"></i> Add to cart</button>
                        <p class="qnt-wrap prod-li-qnt">
                            <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                            <input type="text" value="1" name="cantidad">
                            <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                        </p>
                        <div class="prod-li-favorites">
                            <a href="wishlist.html" class="hover-label add_to_wishlist"><i class="icon ion-heart"></i><span>Add to Wishlist</span></a>
                        </div>
                        <p class="prod-li-compare">
                            <a href="compare.html" class="hover-label prod-li-compare-btn"><span>Compare</span><i class="icon ion-arrow-swap"></i></a>
                        </p>
                    </form>
                </div>
            </div>
            <div class="prod-props">
                {{producto.caracteristica}}
            </div>
        </div>
        <p class="prod-badge">
            <span class="badge-1">TOP SELLER</span>
        </p>
    </div>
    {% include 'includes/catalog/relacionados.html' %}
    </article>
{% endblock %}